spring:
  application:
    name: CarRentalSystem

  datasource:
    url: jdbc:postgresql://localhost:5050/java_db
    username: admin
    password: j@varasul2005

  jpa:
    hibernate:
      show-sql: true
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/liquibase.1.0/changelog-master.yaml
    drop-first: true

server:
  port: 8008